language: rust
rust:
- stable
script:
- "./tests.sh"
deploy:
  provider: releases
  api_key:
    secure: n1snuDCgb5zxTJj01u5hUPodTGOxqkcxf9XQUuWLQ5BBdbjFkwLInItD/Lj1wZN8nDjG5ljkOMZ2mc/InzSW8D9k5/yWlpXlJPF6sKC/58Ff4z70eK8XiT3tULevDzQ0OSGA2TlAxxqzs6sejsXhwMklB5yvJZYoe8MQ1nCUGo39ZEFq7x/kh87PpZakoFmGYeKEnj8/p+eU0M2cw8UnhbMjLexcT32nyZfzb96SpD450i3dYkZOi8jOUp6/6quyxnUYLTPHg/2r2N+f/gvZu/dep38J+qDewlHAuejGN/myF5WHoxmNZwwE6xF/AL01LVGBjV2wlIgyDyHSPwid3jp5jimoxK2r67qpFJUaBPyY1GMoJ0geL8F2I/JJvUV9Q7B+GzZQEX8jBVcamohbpALn/I2uA4KhVK4jqdrgz4kIMNdjaCkoqZ76eBnsVEJt/ZAon6JK0QLuCcixoCpwY9RWm4k4dihd7LRfOa7CLGdnx66ylTrEgPfF4fCK8UtWFbFN7u7ZL3B/s2arWl5Rbejwj8LXuRW7qx+XsQ8WwcAWRW8YHxvz+hhIOxPbDRO3c6bQubgyDUBRY8A7lxEAusjWrJc7y4DPVdhviuB5aVw6/Z9S46Izll5Ts2eXs7xM9vDHqHfpjsSEGV2v7l5qhva6J4rGESrjIQKPlejFVcg=
  file: target/release/tiny-static-web-server
  on:
    repo: sdenel/tiny-static-web-server
    branch: master
