language: rust
rust:
- stable
script:
- "./tests.sh"
deploy:
  provider: releases
  api_key:
    secure: "E1ErfzJ6iTTsdAcC/70zIXqZwdUviTPLlqt8/SvxIfkKPS/AcmUld2tDI4NqwoGX32ye6OSX+cg+vaIEtYZuDfggu/7FsLN4BxHg9BWowDqq4o5XEk6tyTIvdsyxxQzr7douJOuRT4uEqbMZtJgHlCU9ZsbEB6UA3rQgYnpMaZaWUd5bkGryQfcRYmyrlLScoQtWhpt9PhC965ZTeEhT4s4EtAfzenYt5CIu2Bqf3+NrCvRleqg3iIlAiju8c0voo+S73lwGJV6ScmvVFsj+RIBv/lm8XQVgKC4ANUQ4uKpgg3Je37T9gBSCNz2NwV7bJl822ECD5TJv07/IC1L5ZlPYvsnwuPl6JC/mvV2sGZO0QSs71KdmU7GOQkrKAqKrXEtC6+6CpjcNniIYI2Nx54wPGinuFFzISEmLD2WAVbHmB2j08o8U8QKUe8z0D8WXEw9mqYy8v54eLm7yB8gt+qaixnUnbTprCyxO9Pt93cit13Yfvo4ASl6lnajgG4XIjXPefCAaicfwde+9PoGtOXkpo7P9rEBByvtlPMnAUCjBdOippwqTEflqF7rxTsOSbJMxfQKkQnrsHsIirGkOyccukM6AkGKdIDFtOy8YeTEmxn6irB51oFt3G6b3XMr/v+zBtKG04EumfulIFh57qHOeCEWbSXDYBNmUWElZrW4="
  file: "./target/release/tiny-static-web-server"
  on:
    repo: sdenel/tiny-static-web-server
    branch: master

