language: rust
rust:
- stable
script:
- "./tests.sh"
deploy:
  provider: releases
  api_key:
    secure: "V8FJEYlaGCfmFV7A820nvccdGE5NZd+URWEBmQ0cJ51xIcU+C+16jVxFzortm9wUzOjttMIZPfnNpaxSs3VcDp4gWVPk6vSxqjQyfMmxTT4H3Ty/Gmtn0BVo1PaazSBUPW0HyPIRlC/c+KtIbOiW0aSGHTaG8eqcBysXcfLOJJrbdWbsgKd7TEeTM1zS1+7AyeBeUQLTVdlnC3yPldW9B14UbyU1tUlazJx/wIai+qAwEAuQhS302F12i4Fj+HHlRwnqMfwvWt6KHbbMubmuFVmFNqFzFVed+2C/DlWAyeiGTxFBBEDetwEgysDfjWSz5wLbFw2i1eeoLz7oLYf5V/m2BNmc9pyh5HmvtNVoAlIZt5Y97WO9wyZ608wdA/4c+qn9ryEefomywyY4TBEcWl0FFNX7ysOp96TU8YElT4/rqPn/sFWEgJWsSWqYL5idty/QeoVf/Yo+4Q04oW7932fTiM/H50FxWT6MPU4VjOdjEmaEP4jaTsW+qKyWTAyEqe78w1fV9FKzGpC4/unHk70rQAvDnUcpyE3pMRrEAEPkGiP0D3bYWGZHA3XnDsGVnuhIyEVQo91qwsxcGaL0kp7T+Dw5204dQCH/yTBOMoPuOfIYLCWvaFSp3v1ygz5Fw8GkD63hHomx6K98zrj/f2NIoLaAict2Dl9UCkW6CkU="
  file: "./target/release/tiny-static-web-server"
  on:
    repo: sdenel/tiny-static-web-server
    branch: master