language: rust
rust:
- stable
script:
- "./tests.sh"
deploy:
  provider: releases
  api_key:
    secure: r1Z5sCMuqiuKfaHwTaU9RvybB09YSOgIsZQtXeMtmgTnq/EL2+8RaTTPh5eNpYwGV8sr41RxHjLNJcIThMfbi1TJOiSnFeuM3SnJIlVEFXFGTbHa6mhX22CBLVnQNOlCCc6mWoxiiWqY8t8Dx0p+xdU9vc0CK/Xgycgomq+09NGMlAdK+CPANXBluMIL8+76YNigqMngNnPVJaypG/DMr0KsTJJxQIX+tVoj2A4BQDEFm/oSzfxr5iOZv79xhu7AttyXjUEATVjsuYkA0VVXsAX+jpjT4bGF9vBWxU1Z/KD+uSZi+qiAmkI23QAVsCiqg8HYt6UlqaYshr3giWUqxxb5NHXqxp9LGrqbod88k4KYZhoqwUxD23Wx1whII8M0VZoa5boDnkEPwGB7++F/HcDaEsbLnr8NJVDuqgUqn9RmCA4QJkVBnthovwf3y//VHoG9kwI3EUMabE6q9iqrV4V956m6SS7KOl7uP4HjQt/1q1p8OgwfuNFmsPPTlN4FMIimZtmBgPeGsQsM/HKkt0UNwPM0a2V3Q8VtFMBx0BhoksCglSRBp+nkvd3us325wnOA94ZDq8Halv++nqZ1NnbA4R+yUHzshlI3glhOk1+yNllCl1UH6RGlktIDz+8MkyCl2guT4W1tEeuWzVzphwLCLHzYrZDaceT6ugxoL1Q=
  file: target/release/tiny-static-web-server
  on:
    repo: sdenel/tiny-static-web-server
    branch: master
