language: rust
rust:
- nightly
env:
  matrix:
  - SIGNATURE: something
  global:
    secure: bELMC9NqkTLwoxwIWdyF36ioAJDxaBuLdRXj9xbmgJQ4KMZ+IKgkgNC3YydfTv0mJwSgttOwdV8hg50KsR6GQ1rhYK8/PdZ6P8cOj1fXtGt+vg5r/rWTzlTERIAwthXaiDEPtKD4eFJCMnH2WctzR0FSRcq/ikBbVoAQdSsVMPU1m+6H9vX3fWra4JKHC89aytcTi2wlRliEcZRFLyHB9G9m4Itunvkf+mKl0LeJFfwK1MBpTPZop7Mc3e20PiE4wsa08sbwynGzG9teHO/qbhodsJ7nuGqtxBkTuyUat8LvCrTlgZ5/2GeD8LYnVjgKi7ayBPJ4CSyaBDQyEx+RUwnvdH8II+xbU+7G6/A+kIjQyFHarhTS0BHKk7u8lgm9+36/aOoj+gSjxzNTGB6L9yxoWsXYRZgdgT2ekJDp6Dl5km50lUNSxy9T0tmamfBuwzsmB320ED4P1o0l5ZcwRa9Y0n1goy5xNSkD3RDfmgMcViK48s3SmRd+cLrZYUqbhCnzf1NoBH33rQkXFJCpsQzZGUqy0h4Y4/8CafzO579Fpk+n4uEP7Mai092fm+JFR45CkqszweVpayuxm8iE7krGnhS+xiV//YbfgWZbW6Xcy6Yr9JAEsMutQp9e3a/kbFlJYYj6714DAjmlNi+MQl0Mch/pbbtZB+nOCfPqwY0=
script:
- cargo test
- "./tests.sh"
- "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/sdenel/tiny-static-web-server/trigger/$DOCKER_TOKEN/"
deploy:
  provider: releases
  api_key:
    secure: AjW6nyHEe/s58QjgRh7cQUQ2lCIPT38n0GN9hzTQNG741oYGJR9dEOTH7/nOBx+CdR1IHLC/Uzn9OMMCMcuPirgkSaij1L5l4S+R7yE5oRW0tKCZ+zNl+OLNJqOObrm5oHW1qt8xhkMPIbA4Yt2WEoT842RKwtthmemtyrEA6sNMR8xk8+OOfh1DnpLehir/x4HnSaRXweeRF3kBpjPZmAo7X1ilHvHJ73y2oEdkAWOmLcpPZdWtOhA8aPNitU5RWnY9Bdc5DkettEODZvzPK9giqpDXHPP6UfzQc4nMBUVPGliCUUlhqAScS53DcgRwTfH8muUpHzfGtOnd0KanNYodfU4v3KlAD3pU4aty5fhYGlYYmE+wZCXu4nZXLwWiQuq38BChn7+3ESsMM/sUxBt0wKzJZb3rI9gnQO27E1ms2ZLEQfPsZ3zGWrE/EIfsP1/0II/qTda6mv3QNv7ngjVdbHDmbpx09nxjNU1yK/sVDHPeEAmSEYRprHBUnWZd37lElG0iu9Xb41Whfn6wN58HldvrBu4UYFShQyskQP7E2amGc6zpvtYNO9OYeWYi7z0t9MI4xKVBBh/8V3TOyRyvMpsGhow1Duct9etR7P4yx25VIck9t0qw7xrOUoIHNv8v7JfPDczsSqfe9E7+a35t9XPAmN7KMnQytCDiEC4=
  file:
  - "./target/release/tiny-static-web-server"
  skip_cleanup: true
  on:
    repo: sdenel/tiny-static-web-server
    all_branches: true
